<a href="https://colab.research.google.com/github/thoxinloi/ai/blob/main/W8_20_3_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x=[[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
t=[1,1,0,0]
model=Perceptron()
model.fit(x,t)
model.score(x,t)

1.0

In [ ]:
x1=[[0.5,0.5],[-0.3,-0.5],[10,2.3],[-1,-2]]
y1=model.predict(x1)
model.score(x1,y1)
print(y1)

[0 1 0 1]


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
iris=datasets.load_iris()
X=iris.data
y=iris.target
print(X[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.5)
SC=StandardScaler()
SC.fit(X_train)
X_train_std=SC.transform(X_train)
X_test_std=SC.transform(X_test)
print(X_train_std[:5],X_train[:5])
print(y[:5])


[[-1.14410653 -0.33873809 -1.11810608 -1.22138136]
 [-1.14410653 -0.10566142 -1.00976247 -1.09537915]
 [ 0.60232474 -0.57181475  1.15710978  0.9206561 ]
 [-0.79482027  0.59356857 -1.06393427 -1.09537915]
 [ 2.23232726 -1.27104474  1.86134326  1.55066711]] [[4.8 3.  1.4 0.1]
 [4.8 3.1 1.6 0.2]
 [6.3 2.9 5.6 1.8]
 [5.1 3.4 1.5 0.2]
 [7.7 2.6 6.9 2.3]]
[0 0 0 0 0]


In [ ]:
model = Perceptron(max_iter = 40, eta0 = 0.1, random_state=0)
model.fit(X_train_std,y_train)
y_pred= model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Độ chính xác mô hình', accuracy_score(y_test,y_pred))

[2 2 2 2 0 1 2 1 1 2 2 1 1 2 0 2 1 1 2 1 2 2 2 0 0 2 1 2 2 1 0 1 2 2 1 0 0
 1 1 0 2 0 0 2 0 1 1 0 1 0 1 2 1 2 2 1 1 0 2 0 2 2 1 0 2 2 2 1 2 2 1 1 0 1
 1]
[1 2 2 2 0 1 2 1 1 1 2 1 1 2 0 1 1 1 2 2 2 2 2 0 0 1 1 2 2 1 0 1 1 2 2 0 0
 1 1 0 2 0 0 2 0 1 2 0 1 0 1 2 1 2 2 0 1 0 1 0 2 2 1 0 2 2 2 1 2 2 1 1 0 1
 1]
Độ chính xác mô hình 0.8666666666666667


In [ ]:
import pandas as pd
url='crabs.csv'
data=pd.read_csv(url)
import matplotlib.pyplot as plt


In [ ]:
data["sex"].replace({"M":1,"F":0},inplace = True)
data["speies"].replace({'B':1, 'O':0}, inplace = True)
print(data)

     speies  sex  index  fontallip  rearwidth  length  width  depth
0         1    1      1        8.1        6.7    16.1   19.0    7.0
1         1    1      2        8.8        7.7    18.1   20.8    7.4
2         1    1      3        9.2        7.8    19.0   22.4    7.7
3         1    1      4        9.6        7.9    20.1   23.1    8.2
4         1    1      5        9.8        8.0    20.3   23.0    8.2
..      ...  ...    ...        ...        ...     ...    ...    ...
195       0    0     46       21.4       18.0    41.2   46.2   18.7
196       0    0     47       21.7       17.1    41.7   47.2   19.6
197       0    0     48       21.9       17.2    42.6   47.4   19.5
198       0    0     49       22.5       17.2    43.0   48.7   19.8
199       0    0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]
